### ISSUE TITLE
create a README.md

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#14]
As a **recruiter**,

I want to **look at your projects readme and understand**..
- What the app is
- What problem you're solving
- How you solved the problem
- what technologies you used
- what you learned from it

So that **I know why I should hire you** (problem solver, familiar with our tech stack, growth minded etc).

**Comment by shannonscotta** [comment]
https://learn-2.galvanize.com/cohorts/3923/blocks/1013/content_files/01-Blue-Ocean/04-Readme-Template.md

**Comment by gnprwx** [comment]
Looks good, but **key features** and **our solutions** can probably be merged to cover both concepts instead of talking about the features twice in two different sections.
