### ISSUE TITLE
UI/UX: Landing Page Construction

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#17]
As a **client**,

I want to **see what you have envisioned for the application before starting development**,

So that **I know you will be building the product that is right for me**.

**Comment by gnprwx** [comment]
I think this falls under this issue already. https://github.com/longhousefishco/learningsystemapp/issues/13

**Comment by gnprwx** [comment]
Merging into issue #13

**Comment by gnprwx** [comment]
This is mostly done on my end. I will put it in /public after we go over it next week and push it to main when people are happy.

**Comment by gnprwx** [comment]
Completed. Color scheme to be determined.
