### ISSUE TITLE
Migration file created for Database

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#18]
**As a** database admin, 

**I want** to develop migration.sql and seed.sql files, 

**So that** we can easily populate the database with essential data about "git, node, psql etc.", including common commands and their descriptions.

**Comment by shannonscotta** [comment]
going to everyone in the team, asking about useful commands to add

**Comment by JohnGordinier** [comment]
I will work on consolidation of cheatsheet development. I understand an ERD and table relations must be accomplished before database creation, but will work consolidation for myself, then reach out to other on the team.

**Comment by gnprwx** [comment]
Duplicate issue
