### ISSUE TITLE
Create an ERD

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#20]
**As a** developer,

**I want** to create a comprehensive Entity Relationship Diagram,

**so that** we can map out the relationships between topics like "git, node, psql" and their associated commands and descriptions.

**Comment by shannonscotta** [comment]
s-m

**Comment by ethanberke** [comment]
This is what we came up with for our rough draft.  Image and psql files have been sent to Quinn to create migration and seed files.  Open to changes and adjustments.

![Image](https://github.com/mcsp-blue-ocean/quest/assets/140762263/76633668-f246-4bf2-9236-c07ec37fc074)

**Comment by ethanberke** [comment]
New ERD.  Much easier to read and understand.

![Image](https://github.com/mcsp-blue-ocean/quest/assets/140762263/8c858d3b-bdcc-4d7e-9ca1-788cc8dd02f2)

**Comment by gnprwx** [comment]
Completed with other PR.
