### ISSUE TITLE
UI/UX: Create a logo

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#22]

**Comment by JohnGordinier** [comment]
May I create the logo Scott?

**Comment by JohnGordinier** [comment]
I will take this on.

**Comment by JohnGordinier** [comment]
Here are two rough drafts. Please give me feedback on your thoughts. I can go a different direction if needed. 
![First Draft](https://github.com/mcsp-blue-ocean/quest/assets/132930976/acec5d6c-c567-4046-80a9-8ee3335865e7)
![Second Draft](https://github.com/mcsp-blue-ocean/quest/assets/132930976/f31edc77-0506-4cd6-94db-f743608c1d3c)

**Comment by gnprwx** [comment]
The last one is nice. I don't think we're using galvanize, however, but it can be replaced with quest, I would assume. Something like Quest or Q.U.E.S.T. But nothing was solidified on the styling of that acronym.

**Comment by gnprwx** [comment]
I played around with the last icon and it doesn't do well if it's small. This is due to the amount of busy elements involved (code/text). It does work well if it's big, however. But chances are the logo will be small in practical use, so I'd design a logo that looks good small. Thanks!

**Comment by gnprwx** [comment]
John, could you make a mock-up of a logo design with the text Q.U.E.S.T. but the Q being a magnifying glass? I'm curious how that idea would turn out.

**Comment by JohnGordinier** [comment]
That was my plan Greg. It is Quest right..not Q.U.E.S.T.

**Comment by gnprwx** [comment]
It could be either one. Might be interesting to try both variants if possible.

**Comment by JohnGordinier** [comment]
Updated Background with requested changes. Modern Transparent Background.
![QUEST Transparent](https://github.com/mcsp-blue-ocean/quest/assets/132930976/583ad4da-bc71-417f-94dd-5612619713d4)
