### ISSUE TITLE
Create authentication

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#29]
**As a** admin,

**I want** to be able to sign in to the web app,

**So that** I can verify who I am (admin)

**Comment by gnprwx** [comment]
If there is a PR linked to this ticket, it should only be closed when the pull request is approved,

**Comment by gnprwx** [comment]
Tickets do not need to be manually moved to done. They will be moved to done when PR is closed.

**Comment by JohnGordinier** [comment]
Completed with the last PR, which has been approved.

**Comment by gnprwx** [comment]
Pr was not approved. I kicked it back. Check the comments I left on it. #99

**Comment by gnprwx** [comment]
Manually closing...
