### ISSUE TITLE
Link authentication with CRUD routes

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#30]
**As a** admin,

**I want to** be able to "create, read, update, and delete" categories AND commands from the database,

**So that** I can modify the material based on my needs.

**Comment by JohnGordinier** [comment]
Completed with the last PR.

**Comment by gnprwx** [comment]
Pr was not approved. I kicked it back. Check the comments I left on it. #99

**Comment by JohnGordinier** [comment]
Completed the CRUD Routes with the PR that Mark Submitted earlier and is awaiting review.

**Comment by gnprwx** [comment]
PR merged wasn't linked with the issue. Manually closing.
