### ISSUE TITLE
landing page - examples section

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#67]
Ideate on what text makes sense to go here.

![Image](https://github.com/mcsp-blue-ocean/quest/assets/78231948/3b2a8946-7d6a-4d1e-8f8e-73a15a40cc40)

**As a**  user,

**I want** to see the landing page and understand how the website benefits me (specifically the example text area),

**So that** I understand why I should use it.

**Comment by kajiwara12** [comment]
Embark on the Ultimate Coding Quest with QUEST: Quick Understanding of Essential Software Technologies! Unleash the full potential of command line mastery, from Node.js to SQL, Git to React. Elevate your skills with real command examples and let our AI Chatbot be your guide. Join us on a journey where learning meets excitement. Start your QUEST today!"

**Comment by kajiwara12** [comment]
Welcome to QUEST: Your Gateway to Command Line Brilliance! Unravel the intricacies of Node.js, SQL, Git, React, and more with real-world code snippets. Our AI Chatbot is your coding companion, providing answers to your questions in real-time. Join the community on a QUEST for mastery, where every line of code propels you forward. Embrace the power of learning at QUEST!
