### ISSUE TITLE
Landing page - Sign in Modal

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#68]
**As a** admin,

**I want** to be able to click on the "user icon" in the navbar and have a modal render on the landing page,

**So that** I have a way to sign in as admin

**Comment by shannonscotta** [comment]
"user icon"

![Image](https://github.com/mcsp-blue-ocean/quest/assets/78231948/9e89b370-0f73-4117-8a35-7278a4a3ed1e)

**Comment by gnprwx** [comment]
This minimum goal is just to have the login page conditionally render somewhere on the page. Making it a modal can be separate.
