### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#86]
![Image](https://github.com/mcsp-blue-ocean/quest/assets/78231948/d6d95b3c-61c2-474f-a806-24a4276df4d7)

### **Dont forget we want to implement the clipboard for quick copy / paste!**

Create a div that contains each cards "commands", this story is essentially just mapping out everything and then passing over to the UI owner for styling.

**As a** user,

**I want** to click on a "card" and see the related commands,

**So that** I can choose which category of commands to quickly view

**Comment by gnprwx** [comment]
If desired, clicking on the cards for the modal can be a separate issue if the assignee requests as such.

**Comment by gnprwx** [comment]
Manually closing.
